### ISSUE TITLE
Public Repo

### ISSUE THREAD

**Issue by isaacmcdougal** [ElektrazCode/Codewars#2]
Hello,

Please, make this repo private. Read the last paragraph of the [rules section in Codewars code of conduct](https://docs.codewars.com/community/rules#rules) for more information

Thx

**Comment by ElektrazCode** [comment]
I’m so sorry. I wasn’t aware of this rule. I will take care of it immediately. Thank you for bringing it to my attention.
Have a nice day.

Mary Rose Boulos

**Comment by isaacmcdougal** [comment]
No problem, thank you!
